### ISSUE TITLE
Link to Video Dataset is not working

### ISSUE THREAD

**Issue by lilyli3304** [mdyao/HDR-BiTNet#4]
Hi mdyao,

The link to the video dataset is not working. Could you re-share it?
![06](https://github.com/user-attachments/assets/ffe1bb8d-8726-4080-87f2-0e02b0473683)

Many thanks.

Best Regards.

**Comment by mdyao** [comment]
Hi, the link is still accessible on my PC. You might check your proxy settings or try using a VPN to access it.

Please refer to https://drive.google.com/drive/folders/144QYC403NrFXunlsr4k8MXUCxrlauVYH.
![image](https://github.com/user-attachments/assets/6d102b6d-f789-46c7-bf4c-ebe4c1d2653c)
